### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by ThePlenkov** [mongodb-js/url#16]
Trying to parse URL from Pivotal.io:

Failed with log:

2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] module.js:557
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] throw err;
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] ^
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] Error: Cannot find module 'mongodb/lib/read_preference'
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Function.Module._resolveFilename (module.js:555:15)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Function.Module._load (module.js:482:25)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Module.require (module.js:604:17)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at require (internal/module.js:11:18)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Object.<anonymous> (/home/vcap/app/node_modules/mongodb-url/index.js:1:84)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Module._compile (module.js:660:30)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Object.Module._extensions..js (module.js:671:10)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Module.load (module.js:573:32)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at tryModuleLoad (module.js:513:12)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Function.Module._load (module.js:505:3)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Object.<anonymous> (/home/vcap/app/core/clients/mongodb.js:2:13)
2018-01-13T12:53:19.239+01:00 [APP/PROC/WEB/0] [ERR] at Object.<anonymous> (/home/vcap/app/api/api.js:9:12)

Do you have some ideas?

**Comment by durran** [comment]
Have you just recently upgraded to the Node driver 3.0.x? We haven't upgraded our support for that as of yet - would need to be using the Node driver 2.2.x.

**Comment by ThePlenkov** [comment]
I use 9.0.4

**Comment by ThePlenkov** [comment]
However mongodb-uri worked for me as a charm. Sorry!

**Comment by durran** [comment]
Ah ok - great!
